spring:
  application:
    name: SolaceSubscriber

  cloud:
    stream:
      bindings:

        # Subscriber 1 : Email
        userLoginEmail-in-0:
          destination: user/login,ecomm/user/login
          group: email-group

        # Subscriber 2 : Store in DB
        userLoginStore-in-0:
          destination: user/login,ecomm/user/login
          group: store-group

      default-binder: solace
    function:
      definition: userLoginEmail;userLoginStore

# Mail app connection
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/Eventpub
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: mysql

# solace broker connection for message
solace:
  java:
    host: tcp://localhost:55555
    msgVpn: default
    clientUsername: admin
    clientPassword: admin


server:
  port: 8082