spring:
  application:
    name: SolaceSubscriber

  cloud:
    stream:
      bindings:
        userLogin-in-0:
          destination: user/login
          group: email-group  
      default-binder: solace

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true   # 🔥 add this (important)

solace:
  java:
    host: tcp://localhost:55555
    msgVpn: default
    clientUsername: admin
    clientPassword: admin

server:
  port: 8082